//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlsv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLDASV
    {
        public string Ma_DASV { get; set; }
        public string Ma_DA { get; set; }
        public string Ten_DA { get; set; }
        public string The_loai { get; set; }
        public string Ma_SV { get; set; }
        public string Ten_SV { get; set; }
        public string Ma_GV { get; set; }
        public string Ten_GV { get; set; }
        public string Ngay_bat_dau { get; set; }
        public string Ngay_ket_thuc { get; set; }
        public string Link_DA { get; set; }
    
        public virtual QLDA QLDA { get; set; }
        public virtual Tien_do Tien_do { get; set; }
    }
}
