//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlsv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLSV
    {
        public string Ma_SV { get; set; }
        public string Ten_SV { get; set; }
        public string Gioi_tinh { get; set; }
        public string Ngay_sinh { get; set; }
        public string Lop { get; set; }
        public string Dia_chi { get; set; }
        public string SĐT { get; set; }
        public string Email { get; set; }
    
        public virtual Lop Lop1 { get; set; }
    }
}
