//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlsv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tien_do
    {
        public string Ma_DASV { get; set; }
        public string Báo_cáo_tiến_độ_lần_1 { get; set; }
        public string Báo_cáo_giữa_kỳ { get; set; }
        public string Báo_cáo_tiến_độ_lần_3 { get; set; }
        public string Báo_cáo_cuối_kỳ { get; set; }
        public string Link_đồ_án { get; set; }
    
        public virtual QLDASV QLDASV { get; set; }
    }
}
